#!/bin/bash
# LOCAL DEV ONLY: a real snapper 0.13 for this EL9 (AlmaLinux 9) dev
# container, which has no snapper >= 0.12 package, no snapperd/D-Bus and no
# CAP_SYS_ADMIN. Rebuilds the EPEL 10 source RPM (signature checked against
# the EPEL 10 key, in a private rpm database) with three spec changes for EL9:
#   - rpm 4.16 has no %conf section: its configure step moves into %build;
#   - --disable-rollback: rollback's default/active-subvolume queries need
#     CAP_SYS_ADMIN (they'd make `list` fail here) and aren't used by us;
#   - mksubvolume (a rollback helper) isn't built, so it leaves %files.
# Nothing is installed but the build dependencies (dnf, as root); snapper
# itself is unpacked under target/dev-snapper/root, cached across container
# restarts (re-run this after one: it reinstalls missing build deps only if
# it has to rebuild).
#
# Use: scripts/dev-snapper.sh            # build once (or reuse), print the bin dir
#      export GHOSTVOLUMES_DEV_SNAPPER=$PWD/target/dev-snapper
#      cargo test --test snapshot_script   # the e2e tests now use real snapper
#
# target/dev-snapper/bin/snapper is a wrapper: `snapper --no-dbus --root
# "$DEV_SNAPPER_ROOT" …`, with config files under $DEV_SNAPPER_ROOT/etc (so
# never /etc), and the paths `get-config`/`status` print made absolute again
# (as snapper prints them without --root).
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=$PWD/target/dev-snapper
case $OUT in *[!A-Za-z0-9/._-]*) echo "unexpected characters in $OUT" >&2; exit 1;; esac
SRPM=snapper-0.13.0-3.el10_3.src.rpm
SRPM_SHA256=cac00903ffd4e32b1944cf534e9c88942dab800822ca264cb0b7ec4f0026ed32
# EPEL 10, as published on https://fedoraproject.org/security/ (and the key
# the download server offers, which signed $SRPM).
EPEL10_FPR=7D8D15CBFC4E62688591FB2633D98517E37ED158
BASE=https://dl.fedoraproject.org/pub/epel
real() { LD_LIBRARY_PATH="$OUT/root/usr/lib64" "$OUT/root/usr/bin/snapper" "$@"; }

if ! real --version >/dev/null 2>&1; then
  [ "$(id -u)" = 0 ] || { echo "run as root (dnf, rpmbuild)" >&2; exit 1; }
  W=$OUT/work; rm -rf "$W" "$OUT/root"; mkdir -p "$W/db" "$W/src" "$W/top/SPECS" "$W/top/SOURCES"
  dnf -y -q install rpm-build dnf-plugins-core
  curl -fsSL -o "$W/$SRPM" "$BASE/10/Everything/source/tree/Packages/s/$SRPM"
  curl -fsSL -o "$W/epel10.key" "$BASE/RPM-GPG-KEY-EPEL-10"
  echo "$SRPM_SHA256  $W/$SRPM" | sha256sum -c --quiet
  [ "$(gpg --show-keys --with-colons "$W/epel10.key" | awk -F: '$1 == "fpr" {print $10; exit}')" = "$EPEL10_FPR" ] ||
    { echo "EPEL 10 key fingerprint mismatch" >&2; exit 1; }
  rpm --dbpath "$W/db" --initdb
  rpm --dbpath "$W/db" --import "$W/epel10.key"
  rpm --dbpath "$W/db" -K "$W/$SRPM" | grep -q "digests signatures OK" ||
    { echo "$SRPM: bad signature" >&2; exit 1; }
  (cd "$W" && rpm2archive "$SRPM" && tar -xzf "$SRPM.tgz" -C src)
  cp "$W"/src/*.tar.gz "$W"/src/*.patch "$W/top/SOURCES/"
  python3 -I - "$W/src/snapper.spec" "$W/top/SPECS/snapper.spec" <<'EOF'
import sys
s = open(sys.argv[1]).read()
def sub(old, new):
    global s
    assert old in s, old
    s = s.replace(old, new, 1)
sub("%conf\nautoreconf -vfi", "%build\nautoreconf -vfi")
sub("\n%build\n%make_build", "\n%make_build")
sub("  --disable-zypp \\\n", "  --disable-zypp \\\n  --disable-rollback \\\n")
s = "".join(l for l in s.splitlines(True) if "mksubvolume" not in l)
open(sys.argv[2], "w").write(s)
EOF
  dnf -y -q builddep "$W/top/SPECS/snapper.spec"
  rpmbuild --define "_topdir $W/top" --define "debug_package %{nil}" \
    -bb "$W/top/SPECS/snapper.spec" >"$W/build.log" 2>&1 ||
    { tail -30 "$W/build.log" >&2; exit 1; }
  mkdir -p "$OUT/root"
  for p in snapper snapper-libs; do
    rpm2archive -n <"$W/top/RPMS/x86_64/$p-0.13.0-3.el9.x86_64.rpm" | tar -x -C "$OUT/root"
  done
  rm -rf "$W"
fi

mkdir -p "$OUT/bin"
# Written verbatim (quoted heredoc); only @OUT@, checked above, is filled in.
# awk reads the root from the environment, so its value is never code.
sed "s|@OUT@|$OUT|g" >"$OUT/bin/snapper" <<'WRAPPER'
#!/bin/sh
# Generated by scripts/dev-snapper.sh: real snapper, no daemon, config and
# subvolume under $DEV_SNAPPER_ROOT; the paths get-config and status print
# made absolute again (as snapper prints them without --root).
set -eu
: "${DEV_SNAPPER_ROOT:?set DEV_SNAPPER_ROOT}"
run() { LD_LIBRARY_PATH=@OUT@/root/usr/lib64 @OUT@/root/usr/bin/snapper --no-dbus --root "$DEV_SNAPPER_ROOT" "$@"; }
# "SUBVOLUME": "/src"  ->  "SUBVOLUME": "<root>/src", whatever the spacing.
config() {
  awk '{ i = index($0, "\"SUBVOLUME\"")
         if (i) { r = substr($0, i); j = index(r, "\"/")
                  if (j) $0 = substr($0, 1, i - 1) substr(r, 1, j) ENVIRON["DEV_SNAPPER_ROOT"] substr(r, j + 1) }
         print }'
}
# "+..... /src/p"  ->  "+..... <root>/src/p"
status() {
  awk '{ i = index($0, " /"); if (i) $0 = substr($0, 1, i) ENVIRON["DEV_SNAPPER_ROOT"] substr($0, i + 1); print }'
}
out=
prev=
for a in "$@"; do [ "$prev" = -o ] && out=$a; prev=$a; done
case " $* " in
  *" get-config "*) run "$@" | config ;;
  *" status "*) run "$@"; [ -z "$out" ] || { status <"$out" >"$out.abs" && mv "$out.abs" "$out"; } ;;
  *) run "$@" ;;
esac
WRAPPER
chmod +x "$OUT/bin/snapper"
real --version | head -1
echo "$OUT"
