//! TOML data model for `roots.d/*.toml` — the single remaining config
//! fragment kind, since `watched.d` was folded in
//! (`ai-work/tasks/root-watch-config.plan.md`). `projects.d/*.toml` and
//! repo-local `.ghostvolumes.toml` were removed along with `ensure`
//! entirely (`ai-work/tasks/decision-model.plan.md` §7) — decision files
//! are the entire per-project mechanism now (which names, which
//! patterns, approve/deny).
//!
//! A single file: an optional `default-watches` list, plus any number of
//! root-path tables (`["/some/path"]`, via `#[serde(flatten)]`) each with
//! their own optional `enabled`/`watches`. Every field here is
//! `Option<T>`, never `#[serde(default)]`-coerced to a concrete value —
//! `merge.rs`'s layered merge across multiple files needs to tell "this
//! file doesn't mention this field" apart from "this file sets it to the
//! same value the built-in default would produce"; defaults only get
//! applied once, at final resolution after every file in `roots.d/` is
//! merged.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize, PartialEq, Default)]
pub struct RootsFile {
    #[serde(
        rename = "default-watches",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub default_watches: Option<Vec<String>>,
    #[serde(flatten)]
    pub roots: BTreeMap<String, RawRootEntry>,
}

/// One root path's own table. `#[serde(deny_unknown_fields)]` catches a
/// typo'd key (e.g. `enable` for `enabled`) as a parse error rather than
/// silently ignoring it — safe to add here (unlike on `RootsFile` itself,
/// where every non-`default-watches` key is deliberately meant to be
/// accepted as *some* root path via `flatten`).
#[derive(Debug, Deserialize, Serialize, PartialEq, Eq, Default)]
#[serde(deny_unknown_fields)]
pub struct RawRootEntry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub watches: Option<Vec<String>>,
}

pub fn parse_roots(text: &str) -> anyhow::Result<RootsFile> {
    Ok(toml::from_str(text)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_bare_auto_generated_roots() {
        let text = r#"
            # GENERATED by `ghostvolumes scan --save`. Re-run to refresh.
            ["/"]
            ["/home"]
            ["/dbs"]
        "#;
        let parsed = parse_roots(text).unwrap();
        assert_eq!(parsed.default_watches, None);
        assert_eq!(parsed.roots.len(), 3);
        assert_eq!(parsed.roots["/"], RawRootEntry::default());
    }

    #[test]
    fn parses_default_watches_and_per_root_overrides() {
        let text = r#"
            default-watches = ["node_modules", "target", ".venv", "build"]

            ["/home/dracula/git/braindevices/subvolumize-home"]
            watches = ["node_modules", "dist"]

            ["/some/noisy/mount"]
            enabled = false
        "#;
        let parsed = parse_roots(text).unwrap();
        assert_eq!(
            parsed.default_watches,
            Some(vec![
                "node_modules".to_string(),
                "target".to_string(),
                ".venv".to_string(),
                "build".to_string()
            ])
        );
        assert_eq!(
            parsed.roots["/home/dracula/git/braindevices/subvolumize-home"].watches,
            Some(vec!["node_modules".to_string(), "dist".to_string()])
        );
        assert_eq!(parsed.roots["/some/noisy/mount"].enabled, Some(false));
    }

    #[test]
    fn missing_optional_fields_default_to_empty() {
        let parsed = parse_roots("").unwrap();
        assert_eq!(parsed, RootsFile::default());
    }

    #[test]
    fn rejects_malformed_toml() {
        assert!(parse_roots("default-watches = [").is_err());
    }

    #[test]
    fn rejects_a_typo_d_field_in_a_root_table() {
        let err = parse_roots("[\"/x\"]\nenable = true\n").unwrap_err();
        assert!(err.to_string().contains("enable"));
    }

    #[test]
    fn round_trips_through_serialize_and_parse() {
        let mut roots = BTreeMap::new();
        roots.insert(
            "/home".to_string(),
            RawRootEntry {
                enabled: Some(false),
                watches: None,
            },
        );
        roots.insert("/".to_string(), RawRootEntry::default());
        let file = RootsFile {
            default_watches: Some(vec!["node_modules".to_string()]),
            roots,
        };

        let text = toml::to_string(&file).unwrap();
        let parsed = parse_roots(&text).unwrap();
        assert_eq!(parsed, file);
    }
}
