//! TOML data model for the two remaining config fragment kinds:
//! `roots.d/*.toml` and `watched.d/*.toml`. `projects.d/*.toml` and
//! repo-local `.ghostvolumes.toml` were removed along with `ensure`
//! entirely (ai-work/tasks/decision-model.plan.md §7) — decision files
//! are the entire per-project mechanism now (which names, which
//! patterns, approve/deny).

use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize, PartialEq, Eq, Default)]
pub struct RootsFile {
    #[serde(default)]
    pub roots: Vec<String>,
}

#[derive(Debug, Deserialize, PartialEq, Eq, Default)]
pub struct WatchedFile {
    #[serde(default)]
    pub names: Vec<String>,
}

pub fn parse_roots(text: &str) -> anyhow::Result<RootsFile> {
    Ok(toml::from_str(text)?)
}

pub fn parse_watched(text: &str) -> anyhow::Result<WatchedFile> {
    Ok(toml::from_str(text)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_roots_auto_example() {
        let text = r#"
            # GENERATED by `ghostvolumes scan --save`. Re-run to refresh.
            roots = ["/", "/home", "/dbs"]
        "#;
        let parsed = parse_roots(text).unwrap();
        assert_eq!(parsed.roots, vec!["/", "/home", "/dbs"]);
    }

    #[test]
    fn parses_roots_with_commented_out_entries() {
        let text = r#"
            roots = [
                # "/srv/www",
            ]
        "#;
        let parsed = parse_roots(text).unwrap();
        assert!(parsed.roots.is_empty());
    }

    #[test]
    fn parses_watched_defaults_example() {
        let text = r#"names = ["node_modules", "target", ".venv", "build"]"#;
        let parsed = parse_watched(text).unwrap();
        assert_eq!(
            parsed.names,
            vec!["node_modules", "target", ".venv", "build"]
        );
    }

    #[test]
    fn missing_optional_fields_default_to_empty() {
        let text = r#"roots = []"#;
        let parsed = parse_roots(text).unwrap();
        assert!(parsed.roots.is_empty());
    }

    #[test]
    fn rejects_malformed_toml() {
        assert!(parse_roots("roots = [").is_err());
    }
}
