//! TOML data model for the four config fragment kinds described in
//! `ai-work/tasks/main-plan.md` §2: `roots.d/*.toml`, `watched.d/*.toml`,
//! `projects.d/*.toml`, and repo-local `.ghostvolumes.toml`.

use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize, PartialEq, Eq, Default)]
pub struct RootsFile {
    #[serde(default)]
    pub roots: Vec<String>,
}

#[derive(Debug, Deserialize, PartialEq, Eq, Default)]
pub struct WatchedFile {
    #[serde(default)]
    pub names: Vec<String>,
}

#[derive(Debug, Deserialize, PartialEq, Eq, Default)]
pub struct ProjectsFile {
    #[serde(default)]
    pub project: Vec<ProjectEntry>,
}

#[derive(Debug, Deserialize, PartialEq, Eq, Clone)]
pub struct ProjectEntry {
    pub path: String,
    #[serde(default)]
    pub watch: Vec<String>,
    #[serde(default)]
    pub proactive: Vec<String>,
}

/// Repo-local `.ghostvolumes.toml`. Same `watch`/`proactive` shape as a
/// `[[project]]` entry, but `path` is implicit: it's the directory the
/// file was found in (see the cd-hook registration flow in §6).
#[derive(Debug, Deserialize, PartialEq, Eq, Default)]
pub struct RepoLocalFile {
    #[serde(default)]
    pub watch: Vec<String>,
    #[serde(default)]
    pub proactive: Vec<String>,
}

pub fn parse_roots(text: &str) -> anyhow::Result<RootsFile> {
    Ok(toml::from_str(text)?)
}

pub fn parse_watched(text: &str) -> anyhow::Result<WatchedFile> {
    Ok(toml::from_str(text)?)
}

pub fn parse_projects(text: &str) -> anyhow::Result<ProjectsFile> {
    Ok(toml::from_str(text)?)
}

pub fn parse_repo_local(text: &str) -> anyhow::Result<RepoLocalFile> {
    Ok(toml::from_str(text)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_roots_auto_example() {
        let text = r#"
            # GENERATED by `ghostvolumes scan --save`. Re-run to refresh.
            roots = ["/", "/home", "/dbs"]
        "#;
        let parsed = parse_roots(text).unwrap();
        assert_eq!(parsed.roots, vec!["/", "/home", "/dbs"]);
    }

    #[test]
    fn parses_roots_with_commented_out_entries() {
        let text = r#"
            roots = [
                # "/srv/www",
            ]
        "#;
        let parsed = parse_roots(text).unwrap();
        assert!(parsed.roots.is_empty());
    }

    #[test]
    fn parses_watched_defaults_example() {
        let text = r#"names = ["node_modules", "target", ".venv", "build"]"#;
        let parsed = parse_watched(text).unwrap();
        assert_eq!(
            parsed.names,
            vec!["node_modules", "target", ".venv", "build"]
        );
    }

    #[test]
    fn parses_projects_local_example() {
        let text = r#"
            [[project]]
            path      = "/home/user1/projects/big-frontend"
            watch     = ["dist", ".next"]
            proactive = ["node_modules"]

            [[project]]
            path      = "/home/user1/projects/rust-app"
            proactive = ["target"]
        "#;
        let parsed = parse_projects(text).unwrap();
        assert_eq!(parsed.project.len(), 2);
        assert_eq!(parsed.project[0].path, "/home/user1/projects/big-frontend");
        assert_eq!(parsed.project[0].watch, vec!["dist", ".next"]);
        assert_eq!(parsed.project[0].proactive, vec!["node_modules"]);
        assert_eq!(parsed.project[1].path, "/home/user1/projects/rust-app");
        assert!(parsed.project[1].watch.is_empty());
        assert_eq!(parsed.project[1].proactive, vec!["target"]);
    }

    #[test]
    fn missing_optional_fields_default_to_empty() {
        let text = r#"roots = []"#;
        let parsed = parse_roots(text).unwrap();
        assert!(parsed.roots.is_empty());
    }

    #[test]
    fn parses_repo_local_file() {
        let text = r#"
            watch = ["dist"]
            proactive = ["node_modules"]
        "#;
        let parsed = parse_repo_local(text).unwrap();
        assert_eq!(parsed.watch, vec!["dist"]);
        assert_eq!(parsed.proactive, vec!["node_modules"]);
    }

    #[test]
    fn rejects_malformed_toml() {
        assert!(parse_roots("roots = [").is_err());
    }

    #[test]
    fn project_entry_missing_path_is_rejected() {
        let text = r#"
            [[project]]
            watch = ["dist"]
        "#;
        assert!(parse_projects(text).is_err());
    }
}
