//! Repo-local `.ghostvolumes.toml` registration (§6): folds a
//! project-root's repo-local config into `projects.d/00-repo-local.toml`
//! (auto-managed, like `roots.d/00-auto.toml`) the first time `ensure`
//! sees it, or whenever it changes — this is what makes repo-local
//! config a real peer of the global config despite the shim itself
//! never parsing TOML: it turns "this file doesn't exist as far as the
//! reactive path is concerned" into "covered starting from the first
//! interactive `cd` into this repo."

use std::collections::HashMap;
use std::path::Path;

use crate::atomic_write::write_atomically;
use crate::config::{self, ProjectEntry};

const REGISTRY_FILE: &str = "registered.tsv";
const REPO_LOCAL_PROJECTS_FILE: &str = "00-repo-local.toml";

/// Checks `<pwd>/.ghostvolumes.toml`; if present and newer than what's
/// already been folded in (tracked via a small registry file), parses
/// it, folds it into `projects.d/00-repo-local.toml`, and reloads.
/// Returns `true` iff a reload happened (caller should re-read
/// `compiled.tsv`, since it just changed).
pub fn register_if_needed(
    pwd: &Path,
    config_dir: &Path,
    data_dir: &Path,
    cache_path: &Path,
) -> anyhow::Result<bool> {
    let toml_path = pwd.join(".ghostvolumes.toml");
    let Ok(metadata) = std::fs::metadata(&toml_path) else {
        return Ok(false); // no repo-local config here, nothing to do
    };
    let mtime = metadata
        .modified()?
        .duration_since(std::time::UNIX_EPOCH)?
        .as_secs();

    let registry_path = data_dir.join(REGISTRY_FILE);
    let mut registry = read_registry(&registry_path);
    let pwd_key = pwd.to_string_lossy().into_owned();
    if registry.get(&pwd_key) == Some(&mtime) {
        return Ok(false); // already folded in at this exact mtime
    }

    let text = std::fs::read_to_string(&toml_path)?;
    let parsed = config::parse_repo_local(&text)?;
    fold_into_repo_local_projects(config_dir, &pwd_key, &parsed)?;

    registry.insert(pwd_key, mtime);
    write_registry(&registry_path, &registry)?;

    crate::reload::reload(config_dir, cache_path)?;
    Ok(true)
}

fn read_registry(path: &Path) -> HashMap<String, u64> {
    let Ok(text) = std::fs::read_to_string(path) else {
        return HashMap::new();
    };
    text.lines()
        .filter_map(|line| {
            let (path, mtime) = line.split_once('\t')?;
            Some((path.to_string(), mtime.parse().ok()?))
        })
        .collect()
}

fn write_registry(path: &Path, registry: &HashMap<String, u64>) -> anyhow::Result<()> {
    let mut entries: Vec<_> = registry.iter().collect();
    entries.sort(); // deterministic output
    let mut text = String::new();
    for (path, mtime) in entries {
        text.push_str(&format!("{path}\t{mtime}\n"));
    }
    write_atomically(path, &text)
}

/// Replaces any existing entry for `project_path` (a repo can be
/// re-registered after editing `.ghostvolumes.toml`) and rewrites the
/// whole auto-managed file.
fn fold_into_repo_local_projects(
    config_dir: &Path,
    project_path: &str,
    parsed: &config::RepoLocalFile,
) -> anyhow::Result<()> {
    let file_path = config_dir.join("projects.d").join(REPO_LOCAL_PROJECTS_FILE);
    let existing_text = std::fs::read_to_string(&file_path).unwrap_or_default();
    let mut projects: Vec<ProjectEntry> = config::parse_projects(&existing_text)
        .map(|f| f.project)
        .unwrap_or_default();
    projects.retain(|p| p.path != project_path);
    projects.push(ProjectEntry {
        path: project_path.to_string(),
        watch: parsed.watch.clone(),
        proactive: parsed.proactive.clone(),
    });
    projects.sort_by(|a, b| a.path.cmp(&b.path)); // deterministic output

    let mut out = String::from(
        "# GENERATED by `ghostvolumes ensure`'s .ghostvolumes.toml registration (§6).\n\
         # Do not hand-edit — re-running ensure in the source repo regenerates this.\n\n",
    );
    for p in &projects {
        out.push_str("[[project]]\n");
        out.push_str(&format!("path = {:?}\n", p.path));
        if !p.watch.is_empty() {
            out.push_str(&format!("watch = {:?}\n", p.watch));
        }
        if !p.proactive.is_empty() {
            out.push_str(&format!("proactive = {:?}\n", p.proactive));
        }
        out.push('\n');
    }
    write_atomically(&file_path, &out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn dirs() -> (
        tempfile::TempDir,
        std::path::PathBuf,
        std::path::PathBuf,
        std::path::PathBuf,
    ) {
        let root = tempdir().unwrap();
        let config_dir = root.path().join("config");
        let data_dir = root.path().join("data");
        let cache_path = data_dir.join("compiled.tsv");
        std::fs::create_dir_all(&data_dir).unwrap();
        (root, config_dir, data_dir, cache_path)
    }

    #[test]
    fn no_ghostvolumes_toml_is_a_noop() {
        let (root, config_dir, data_dir, cache_path) = dirs();
        let pwd = root.path().join("project");
        std::fs::create_dir_all(&pwd).unwrap();

        let reloaded = register_if_needed(&pwd, &config_dir, &data_dir, &cache_path).unwrap();
        assert!(!reloaded);
        assert!(!config_dir.join("projects.d/00-repo-local.toml").exists());
    }

    #[test]
    fn registers_a_new_repo_local_config_and_reloads() {
        let (root, config_dir, data_dir, cache_path) = dirs();
        let pwd = root.path().join("project");
        std::fs::create_dir_all(&pwd).unwrap();
        std::fs::write(
            pwd.join(".ghostvolumes.toml"),
            "watch = [\"dist\"]\nproactive = [\"node_modules\"]\n",
        )
        .unwrap();

        let reloaded = register_if_needed(&pwd, &config_dir, &data_dir, &cache_path).unwrap();
        assert!(reloaded);

        let written =
            std::fs::read_to_string(config_dir.join("projects.d/00-repo-local.toml")).unwrap();
        let parsed = config::parse_projects(&written).unwrap();
        assert_eq!(parsed.project.len(), 1);
        assert_eq!(parsed.project[0].path, pwd.to_string_lossy());
        assert_eq!(parsed.project[0].watch, vec!["dist".to_string()]);
        assert_eq!(
            parsed.project[0].proactive,
            vec!["node_modules".to_string()]
        );

        // reload() ran, so compiled.tsv now reflects the new project.
        let cache_text = std::fs::read_to_string(&cache_path).unwrap();
        assert!(cache_text.contains("node_modules\tproactive"));
    }

    #[test]
    fn does_not_reregister_the_same_unchanged_file() {
        let (root, config_dir, data_dir, cache_path) = dirs();
        let pwd = root.path().join("project");
        std::fs::create_dir_all(&pwd).unwrap();
        std::fs::write(pwd.join(".ghostvolumes.toml"), "proactive = [\"target\"]\n").unwrap();

        assert!(register_if_needed(&pwd, &config_dir, &data_dir, &cache_path).unwrap());
        assert!(!register_if_needed(&pwd, &config_dir, &data_dir, &cache_path).unwrap());
    }

    #[test]
    fn reregisters_after_the_file_is_modified() {
        let (root, config_dir, data_dir, cache_path) = dirs();
        let pwd = root.path().join("project");
        std::fs::create_dir_all(&pwd).unwrap();
        let toml_path = pwd.join(".ghostvolumes.toml");
        std::fs::write(&toml_path, "proactive = [\"target\"]\n").unwrap();
        assert!(register_if_needed(&pwd, &config_dir, &data_dir, &cache_path).unwrap());

        // Force a distinct mtime (some filesystems have 1s resolution).
        let new_mtime = std::time::SystemTime::now() + std::time::Duration::from_secs(2);
        std::fs::write(&toml_path, "proactive = [\"target\", \"node_modules\"]\n").unwrap();
        std::fs::File::open(&toml_path)
            .unwrap()
            .set_modified(new_mtime)
            .unwrap();

        assert!(register_if_needed(&pwd, &config_dir, &data_dir, &cache_path).unwrap());
        let written =
            std::fs::read_to_string(config_dir.join("projects.d/00-repo-local.toml")).unwrap();
        let parsed = config::parse_projects(&written).unwrap();
        assert_eq!(parsed.project[0].proactive, vec!["target", "node_modules"]);
    }

    #[test]
    fn multiple_repos_accumulate_without_clobbering_each_other() {
        let (root, config_dir, data_dir, cache_path) = dirs();
        let a = root.path().join("a");
        let b = root.path().join("b");
        std::fs::create_dir_all(&a).unwrap();
        std::fs::create_dir_all(&b).unwrap();
        std::fs::write(a.join(".ghostvolumes.toml"), "proactive = [\"target\"]\n").unwrap();
        std::fs::write(
            b.join(".ghostvolumes.toml"),
            "proactive = [\"node_modules\"]\n",
        )
        .unwrap();

        register_if_needed(&a, &config_dir, &data_dir, &cache_path).unwrap();
        register_if_needed(&b, &config_dir, &data_dir, &cache_path).unwrap();

        let written =
            std::fs::read_to_string(config_dir.join("projects.d/00-repo-local.toml")).unwrap();
        let parsed = config::parse_projects(&written).unwrap();
        assert_eq!(parsed.project.len(), 2);
    }
}
