//! `ghostvolumes roots enable/disable`: toggles a root's `enabled`
//! field in a dedicated `roots.d/10-disable.toml`, never touching
//! `00-auto.toml` (regenerated by `scan --save`) or any hand-edited
//! file. `disable` records `enabled = false`; `enable` removes the
//! entry entirely, reverting to the default (enabled).

use std::path::{Path, PathBuf};

use crate::atomic_write::write_atomically;
use crate::config::RootsFile;

fn disabled_roots_path(config_dir: &Path) -> PathBuf {
    config_dir
        .join(crate::filenames::ROOTS_D_DIR)
        .join(crate::filenames::DISABLED_ROOTS_FILE_NAME)
}

fn lock_disabled_roots(config_dir: &Path) -> anyhow::Result<std::fs::File> {
    let lock_path = config_dir
        .join(crate::filenames::ROOTS_D_DIR)
        .join(crate::filenames::DISABLED_ROOTS_LOCK_FILE_NAME);
    let lock_file = crate::lock::open_lock_file(&lock_path)?;
    lock_file.lock()?;
    Ok(lock_file)
}

fn read_disabled_roots(file_path: &Path) -> anyhow::Result<RootsFile> {
    match std::fs::read_to_string(file_path) {
        Ok(text) => crate::config::parse_roots(&text),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(RootsFile::default()),
        Err(e) => Err(e.into()),
    }
}

fn write_disabled_roots(file_path: &Path, file: &RootsFile) -> anyhow::Result<()> {
    write_atomically(file_path, &toml::to_string(file)?)
}

pub fn disable(config_dir: &Path, path: &str) -> anyhow::Result<()> {
    let path = crate::project_roots::normalize_root_path(path);
    let file_path = disabled_roots_path(config_dir);
    let _lock = lock_disabled_roots(config_dir)?;

    let mut file = read_disabled_roots(&file_path)?;
    file.roots.entry(path).or_default().enabled = Some(false);
    write_disabled_roots(&file_path, &file)
}

pub fn enable(config_dir: &Path, path: &str) -> anyhow::Result<()> {
    let path = crate::project_roots::normalize_root_path(path);
    let file_path = disabled_roots_path(config_dir);
    let _lock = lock_disabled_roots(config_dir)?;

    let mut file = read_disabled_roots(&file_path)?;
    file.roots.remove(&path);
    write_disabled_roots(&file_path, &file)
}

/// Every currently-disabled root path, read-only, no lock needed — for
/// `roots enable`'s own completion candidates.
pub fn list_disabled(config_dir: &Path) -> Vec<String> {
    read_disabled_roots(&disabled_roots_path(config_dir))
        .map(|file| file.roots.into_keys().collect())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn read_back(config_dir: &Path) -> RootsFile {
        read_disabled_roots(&disabled_roots_path(config_dir)).unwrap()
    }

    #[test]
    fn disable_records_enabled_false_in_its_own_file() {
        let config_dir = tempdir().unwrap();
        disable(config_dir.path(), "/mnt/noisy").unwrap();

        let file = read_back(config_dir.path());
        assert_eq!(file.roots["/mnt/noisy"].enabled, Some(false));
    }

    #[test]
    fn disable_normalizes_a_trailing_slash() {
        let config_dir = tempdir().unwrap();
        disable(config_dir.path(), "/mnt/noisy/").unwrap();

        let file = read_back(config_dir.path());
        assert!(file.roots.contains_key("/mnt/noisy"));
        assert!(!file.roots.contains_key("/mnt/noisy/"));
    }

    #[test]
    fn disable_is_idempotent() {
        let config_dir = tempdir().unwrap();
        disable(config_dir.path(), "/mnt/noisy").unwrap();
        disable(config_dir.path(), "/mnt/noisy").unwrap();

        let file = read_back(config_dir.path());
        assert_eq!(file.roots.len(), 1);
        assert_eq!(file.roots["/mnt/noisy"].enabled, Some(false));
    }

    #[test]
    fn enable_removes_a_disabled_entry() {
        let config_dir = tempdir().unwrap();
        disable(config_dir.path(), "/mnt/noisy").unwrap();
        enable(config_dir.path(), "/mnt/noisy").unwrap();

        let file = read_back(config_dir.path());
        assert!(!file.roots.contains_key("/mnt/noisy"));
    }

    #[test]
    fn enable_on_an_untouched_root_is_a_harmless_no_op() {
        let config_dir = tempdir().unwrap();
        enable(config_dir.path(), "/never/disabled").unwrap();

        let file = read_back(config_dir.path());
        assert!(file.roots.is_empty());
    }

    #[test]
    fn disable_never_touches_other_roots_d_files() {
        let config_dir = tempdir().unwrap();
        let roots_d = config_dir.path().join(crate::filenames::ROOTS_D_DIR);
        std::fs::create_dir_all(&roots_d).unwrap();
        std::fs::write(
            roots_d.join(crate::filenames::AUTO_ROOTS_FILE_NAME),
            "[\"/\"]\n",
        )
        .unwrap();

        disable(config_dir.path(), "/mnt/noisy").unwrap();

        let auto =
            std::fs::read_to_string(roots_d.join(crate::filenames::AUTO_ROOTS_FILE_NAME)).unwrap();
        assert_eq!(auto, "[\"/\"]\n");
    }

    #[test]
    fn disable_preserves_an_already_disabled_sibling_root() {
        let config_dir = tempdir().unwrap();
        disable(config_dir.path(), "/mnt/first").unwrap();
        disable(config_dir.path(), "/mnt/second").unwrap();

        let file = read_back(config_dir.path());
        assert_eq!(file.roots["/mnt/first"].enabled, Some(false));
        assert_eq!(file.roots["/mnt/second"].enabled, Some(false));
    }

    #[test]
    fn list_disabled_reflects_disable_and_enable() {
        let config_dir = tempdir().unwrap();
        assert!(list_disabled(config_dir.path()).is_empty());

        disable(config_dir.path(), "/mnt/noisy").unwrap();
        assert_eq!(list_disabled(config_dir.path()), vec!["/mnt/noisy"]);

        enable(config_dir.path(), "/mnt/noisy").unwrap();
        assert!(list_disabled(config_dir.path()).is_empty());
    }
}
