//! `ghostvolumes scan` / `scan --save` (§3): unprivileged BTRFS
//! snapshot-root detection. For each BTRFS mountpoint, a `.snapshots`
//! child that is itself a subvolume (inode 256) is Snapper's
//! structural fingerprint — present regardless of whether `.snapshots`
//! has its own separate mount entry (openSUSE-style) or is just a
//! nested, unmounted subvolume (Arch-style), since a plain `stat()`
//! sees it either way.
//!
//! The privileged pass (§3 point 2: `snapper list-configs`, Timeshift,
//! btrbk config parsing, only run under `sudo`) is not implemented
//! yet — out of scope for this step, which covers the always-run
//! unprivileged pass and the `scan`/`scan --save` command shape.

use std::path::Path;

use crate::atomic_write::write_atomically;
use crate::config::{RawRootEntry, RootsFile};
use crate::{btrfs, filenames, mountinfo};

const HEADER: &str = "# GENERATED by `ghostvolumes scan --save`. Re-run to refresh.\n\
                       # Manual additions belong in roots.d/10-local.toml instead.\n";

/// `true` iff `mountpoint` has a `.snapshots` child that's itself a
/// BTRFS subvolume — Snapper's structural fingerprint (§3).
fn is_snapshot_managed(mountpoint: &Path) -> bool {
    btrfs::is_subvolume(&mountpoint.join(".snapshots")).unwrap_or(false)
}

/// Auto-detected roots: BTRFS mountpoints (from `mountinfo_text`) that
/// are Snapper-managed. Sorted for deterministic output.
fn detect_roots_from_text(mountinfo_text: &str) -> Vec<String> {
    let mut roots: Vec<String> = mountinfo::btrfs_mountpoints(mountinfo_text)
        .into_iter()
        .filter(|mountpoint| is_snapshot_managed(Path::new(mountpoint)))
        .collect();
    roots.sort();
    roots.dedup();
    roots
}

/// Real entry point: reads the live `/proc/self/mountinfo`.
pub fn detect_roots() -> anyhow::Result<Vec<String>> {
    let text = std::fs::read_to_string("/proc/self/mountinfo")?;
    Ok(detect_roots_from_text(&text))
}

/// Renders and atomically writes `roots.d/00-auto.toml`. Never touches
/// any other file under `config_dir` (§2). Writes bare root-path
/// entries only — no `default-watches`, no per-root `enabled`/`watches`
/// override, since `scan` only ever knows *which* paths are BTRFS
/// roots, not how they should be watched; that's `10-local.toml`'s job.
pub fn save_roots(config_dir: &Path, roots: &[String]) -> anyhow::Result<()> {
    let file = RootsFile {
        default_watches: None,
        default_ignore: None,
        roots: roots
            .iter()
            .map(|r| (r.clone(), RawRootEntry::default()))
            .collect(),
    };
    let body = toml::to_string(&file)?;
    let text = format!("{HEADER}{body}");
    write_atomically(
        &config_dir
            .join(filenames::ROOTS_D_DIR)
            .join(filenames::AUTO_ROOTS_FILE_NAME),
        &text,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_support::btrfs_scratch_dir;
    use tempfile::tempdir;

    fn fake_mountinfo_line(mountpoint: &Path) -> String {
        format!(
            "36 35 0:31 / {} rw,relatime shared:1 - btrfs /dev/sda2 rw,ssd\n",
            mountpoint.display()
        )
    }

    #[test]
    fn mountpoint_with_snapshots_subvolume_is_detected() {
        let dir = btrfs_scratch_dir();
        btrfs::create_subvolume(dir.path(), ".snapshots").unwrap();

        let text = fake_mountinfo_line(dir.path());
        let roots = detect_roots_from_text(&text);
        assert_eq!(roots, vec![dir.path().to_str().unwrap().to_string()]);
    }

    #[test]
    fn mountpoint_with_plain_snapshots_directory_is_not_detected() {
        // Arch/openSUSE both require .snapshots to be a *subvolume*,
        // not just a regular directory that happens to be named that.
        let dir = btrfs_scratch_dir();
        std::fs::create_dir(dir.path().join(".snapshots")).unwrap();

        let text = fake_mountinfo_line(dir.path());
        assert!(detect_roots_from_text(&text).is_empty());
    }

    #[test]
    fn mountpoint_with_no_snapshots_at_all_is_not_detected() {
        let dir = btrfs_scratch_dir();
        let text = fake_mountinfo_line(dir.path());
        assert!(detect_roots_from_text(&text).is_empty());
    }

    #[test]
    fn non_btrfs_mountpoint_is_never_a_candidate_even_with_snapshots_dir() {
        let dir = tempdir().unwrap(); // overlayfs, not BTRFS
        std::fs::create_dir(dir.path().join(".snapshots")).unwrap();
        let text = format!(
            "36 35 0:31 / {} rw,relatime shared:1 - ext4 /dev/sda2 rw\n",
            dir.path().display()
        );
        assert!(detect_roots_from_text(&text).is_empty());
    }

    #[test]
    fn results_are_sorted_and_deduped() {
        let a = btrfs_scratch_dir();
        let b = btrfs_scratch_dir();
        btrfs::create_subvolume(a.path(), ".snapshots").unwrap();
        btrfs::create_subvolume(b.path(), ".snapshots").unwrap();

        let mut paths = [a.path().to_path_buf(), b.path().to_path_buf()];
        paths.sort();
        let text = format!(
            "{}{}{}",
            fake_mountinfo_line(&paths[0]),
            fake_mountinfo_line(&paths[1]),
            fake_mountinfo_line(&paths[0]), // duplicate line
        );

        let roots = detect_roots_from_text(&text);
        assert_eq!(
            roots,
            vec![
                paths[0].to_str().unwrap().to_string(),
                paths[1].to_str().unwrap().to_string()
            ]
        );
    }

    #[test]
    fn save_roots_writes_only_roots_d_00_auto_and_nothing_else() {
        let config_dir = tempdir().unwrap();
        let roots_d = config_dir.path().join(filenames::ROOTS_D_DIR);
        // Pre-existing hand-edited file must survive untouched (§2:
        // "scan --save only ever writes roots.d/00-auto.toml").
        std::fs::create_dir_all(&roots_d).unwrap();
        std::fs::write(roots_d.join("10-local.toml"), "[\"/srv/www\"]\n").unwrap();

        save_roots(config_dir.path(), &["/".to_string(), "/home".to_string()]).unwrap();

        let written =
            std::fs::read_to_string(roots_d.join(filenames::AUTO_ROOTS_FILE_NAME)).unwrap();
        assert!(written.starts_with("# GENERATED by `ghostvolumes scan --save`"));
        let parsed: RootsFile = toml::from_str(&written).unwrap();
        assert_eq!(parsed.roots.len(), 2);
        assert!(parsed.roots.contains_key("/"));
        assert!(parsed.roots.contains_key("/home"));

        let untouched = std::fs::read_to_string(roots_d.join("10-local.toml")).unwrap();
        assert_eq!(untouched, "[\"/srv/www\"]\n");
    }

    #[test]
    fn save_roots_is_a_valid_toml_roundtrip_via_merge_load_all() {
        let config_dir = tempdir().unwrap();
        save_roots(config_dir.path(), &["/data/workspaces".to_string()]).unwrap();

        let merged = crate::merge::load_all(config_dir.path()).unwrap();
        assert_eq!(merged.roots.len(), 1);
        assert_eq!(merged.roots[0].path, "/data/workspaces");
    }
}
